### ISSUE TITLE
Styling componement's surrounding <div>

### ISSUE THREAD

**Issue by ang-st** [apertureless/vue-chartjs#70]
Hello, 
i try to center a chart in a grid system and AFAIK found that components add a div that can't be reached for styling. Example [here](https://github.com/apertureless/vue-chartjs/blob/master/src/BaseCharts/Bar.js#L8)

### Expected Behavior
Maybe a prop that can allow passing class or styling properties 

### Actual Behavior
Not implemented, i might propose a P/R if needed

### Environment
- vue.js version: 2.1.0
- vue-chart.js version: 2.5.3
- npm version: 3.10.10

Thanks for you time on this project

**Comment by apertureless** [comment]
Hey! 

Well vue template renderer always needs a root node to render the template.  And the canvas element itself can't be the root node.

Thats why there is a div.

However I don't really understand what you mean by centering the chart and why you should not be able to do so.

If you pass the responsive true option, the canvas will fill out your div and grow and shrink with it. So you can style it and center it how you want.

**Comment by rzb** [comment]
I was facing the same problem. 

In my use case, I do want responsiveness, but I don't want the chart to grow above a specific width.

Although it's not possible to directly target the root node, you can always use another wrapper div, like so:

``` css
.my-wrapper {
    display: flex;
    justify-content: center;
}
.my-wrapper > div {
    max-width: 300px; // only necessary if you do not want your responsive chart to grow infinitely
}
```

That does the trick. But it led me to another issue #79.
