### ISSUE TITLE
[Bug]: Module not found: Error: Can't resolve 'vue-chartjs' 

### ISSUE THREAD

**Issue by pablo-johnson** [apertureless/vue-chartjs#928]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I am using yarn as the dependency manager.

When running the project with yarn serve everything works as expected.

When running the project via docker-compose, I got the following error

```
frontend  |  error  in ./src/components/BarChart.vue?vue&type=script&lang=js
frontend  | 
frontend  | Module not found: Error: Can't resolve 'vue-chartjs' in '/frontend/src/components'
frontend  | 
frontend  |  error  in ./src/components/BarChart.vue?vue&type=script&lang=js
frontend  | 
frontend  | Module not found: Error: Can't resolve 'chart.js' in '/frontend/src/components'
```

This is my dockerfile content

```
FROM node:lts-alpine

WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH

COPY package.json /frontend/package.json

RUN yarn install

EXPOSE 3001
```

And this is my docker-compose.yaml content

```
version: "3.8"
services:
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/frontend/
      - "/frontend/node_modules"
    command: yarn serve
    env_file:
      - ./frontend/.env
    ports:
      - '3001:3001'
```
The BarChart.vue component

```
<template>
  <Bar
    :chart-options="chartOptions"
    :chart-data="chartData"
    :chart-id="chartId"
    :dataset-id-key="datasetIdKey"
    :plugins="plugins"
    :css-classes="cssClasses"
    :styles="styles"
    :width="width"
    :height="height"
  />
</template>

<script>
import { Bar } from 'vue-chartjs'
import { Chart as ChartJS, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale } from 'chart.js'

ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale)

export default {
  name: 'BarChart',
  components: { Bar },
  props: {
    chartId: {
      type: String,
      default: 'bar-chart'
    },
    datasetIdKey: {
      type: String,
      default: 'label'
    },
    width: {
      type: Number,
      default: 400
    },
    height: {
      type: Number,
      default: 400
    },
    cssClasses: {
      default: '',
      type: String
    },
    styles: {
      type: Object,
      default: () => {}
    },
    plugins: {
      type: Object,
      default: () => {}
    }
  },
  data() {
    return {
      chartData: {
        labels: [ 'January', 'February', 'March' ],
        datasets: [ { data: [40, 20, 12] } ]
      },
      chartOptions: {
        responsive: true
      }
    }
  }
}
</script>
```

### Reproduction

Its difficult to reproduce this without docker installed

### chart.js version

3.9.1

### vue-chartjs version

4.1.2
